### ISSUE TITLE
Factor out `needs_packages()`

### ISSUE THREAD

**Issue by salim-b** [r-hub/pkgsearch#102]
I just submitted #101 and now I'm wondering: Are there any plans on factoring out the `needs_packages()` function into a separate package? Or maybe introduce something similar in [pak](https://pak.r-lib.org/)?

Currently, the function looks like this:

https://github.com/r-hub/pkgsearch/blob/9c0102e85929f25d23cb4f497ba4f01c3d3c0cd9/R/utils.R#L100-L127

This implementation of course is not very sophisticated and it could be improved (i.a. provide an auto-generated code snippet to install the missing packages in the error message).

But it still provides a frequently used check: Test if package xyz, which is only _suggested_ but not _imported_, is installed and if not, throw an informative error. I would really like to have a "standardized" way to do this!

**Comment by gaborcsardi** [comment]
Hi, yeah, I would not export this from pkgsearch. 

It seems like you want to use this programmatically. I think introducing a new dependency for these 10 lines of mostly trivial code is probably not worth it, so I would say just copy this function into your package(s). 

FWIW, there is also `rlang::is_installed()`

**Comment by salim-b** [comment]
> yeah, I would not export this from pkgsearch.

Sure, I didn't really mean to export it in the _current_ form, sorry for being a bit unclear. I was rather asking if there are any plans on your side (the people around tidyverse, r-lib, r-hub, RStudio etc.) on introducing such a function in a new (or existing, e.g. pak) package in the near future. 🙂

After all, it's an action that's frequently used in a lot of packages and it would be cool to have a _best practice_ implementation in one place (kinda like `rlang::arg_match()` for argument matching).

But I guess your answer means there are no such plans, right?

> FWIW, there is also `rlang::is_installed()`

Thanks for the hint! I just created https://github.com/r-lib/rlang/pull/991 to make it vectorized... I hope you're not about to rip it right out of the air. 😅
