### ISSUE TITLE
All search returning 0 results

### ISSUE THREAD

**Issue by systemnova** [r-hub/pkgsearch#107]
This package has been an invaluable tool that I've come to depend on heavily. Thanks for creating it!

I went to use it today and noticed that on both my desktop & Rstudio server instance the search function is returning 0 results, regardless of the search term. This also happens in the add-in. Any help to troubleshoot would be much appreciated.

**Comment by systemnova** [comment]
Seemed to resolve itself, maybe the server was briefly down, although no errors were thrown?

**Comment by systemnova** [comment]
Actually, still has some odd behaviour with the download count showing as 1 for all packages?

**Comment by gaborcsardi** [comment]
Yes, emergency update for the `log4j` disaster. Will fix the download counts later today.

**Comment by gaborcsardi** [comment]
This was fixed, I believe.
