### ISSUE TITLE
pkg_search() timeout error

### ISSUE THREAD

**Issue by eyildiztepe** [r-hub/pkgsearch#111]
I'm getting timeout error for the pkg_search() function.

library("pkgsearch")
pkg_search("permutation test")

**Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached: [search.r-pkg.org:80] Connection timed out after 10012 milliseconds**

**Comment by gaborcsardi** [comment]
This applies to pkgsearch as well, unfortunately:

> Hi all, unfortunately we temporarily need to stop our Windows and Linux builders, to sort out some billing issues. Hopefully we'll be able to turn them back on soon. We'll tweet here once we have more information.

https://twitter.com/rhub_/status/1542039387369885698

**Comment by gaborcsardi** [comment]
It is up and running again.

**Comment by gladkia** [comment]
Hi @gaborcsardi. The issue is back: 
```
> pkgsearch::pkg_search("permutation test")
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached: [search.r-pkg.org:80] Connection timeout after 10000 ms
```

**Comment by gaborcsardi** [comment]
Indeed. Unexpected infrastructure failure. Will try to finish the fix today. Status page, btw: https://status.r-pkg.org/

**Comment by gladkia** [comment]
Thanks for the quick response :)!

**Comment by gaborcsardi** [comment]
OK, it should work again now. I haven't fixed the updating yet, so the data is a couple of days stale, e.g. brand new package are missing. I'll keep this issue open until the updating is fixed.

**Comment by gaborcsardi** [comment]
OK, it is updating properly now, both for new / archived packages, and also for the download and revdep numbers.
