### ISSUE TITLE
The information obtained by `ps()` is seriously delayed

### ISSUE THREAD

**Issue by chuxinyuan** [r-hub/pkgsearch#119]
``` r
pkgsearch::ps("ipkg")
#> - "ipkg" ----------------------------------------- 1 package in 0.008 seconds -
#>   #     package version by            @ title                                  
#>  1  100 ipkg    1.0.5   Xinyuan Chu  1y Install R Packages on GitHub from Hu...
```

<sup>Created on 2023-10-12 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

ipkg v1.0.5 was released to cran on 2022-05-28, and the latest version is v1.0.9.

See details：<https://cran.r-project.org/package=ipkg>

**Comment by gaborcsardi** [comment]
Thanks for the heads up, fixed now.
