### ISSUE TITLE
merge crandb into pkgsearch

### ISSUE THREAD

**Issue by maelle** [r-hub/pkgsearch#15]
Only once crandb has less dependencies... and passing tests.

**Comment by maelle** [comment]
``` r
crandb_f <- ls(getNamespace("crandb"), all.names=TRUE)
pkgsearch_f <- ls(getNamespace("pkgsearch"), all.names=TRUE)

any(crandb_f %in% pkgsearch_f)
#> [1] TRUE
crandb_f[crandb_f %in% pkgsearch_f]
#> [1] "."                    ".__NAMESPACE__."      ".__S3MethodsTable__."
#> [4] ".packageName"         "%+%"                  "%||%"
```

<sup>Created on 2019-05-09 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by gaborcsardi** [comment]
Yeah, only the last two matter I guess, the dot is probably just a check fix. So check how they are defined. Hopefully they are the same.

**Comment by maelle** [comment]
Yes, I looked, they are the same :tada:

**Comment by maelle** [comment]
Now I get trouble with `document()`, probably due to Markdown vs non Markdown syntax (but the error message is about utils.R not being found :confused: )

**Comment by maelle** [comment]
```r
> document()
Updating pkgsearch documentation
Error in file(con, "r") : cannot open the connection
In addition: Warning messages:
1: In normalizePath(file.path(path, "R", collate)) :
  path[4]="/home/maelle/Documents/R-hub/pkgsearch/R/utils.r": No such file or directory
2: In normalizePath(rfiles, winslash = "/") :
  path[4]="/home/maelle/Documents/R-hub/pkgsearch/R/utils.r": No such file or directory
3: In file(con, "r") :
  cannot open file '/home/maelle/Documents/R-hub/pkgsearch/R/utils.r': No such file or directory
```

**Comment by gaborcsardi** [comment]
`utils.r` is not in the `Collate`?

**Comment by gaborcsardi** [comment]
Or actually, the other way, it is in the `Collate`, but it does not exist any more. Or there is a `#' @include utils.r` somewhere.

**Comment by maelle** [comment]
`#' @include utils.r` it was, thanks a ton!!

**Comment by maelle** [comment]
- [ ] Merge

- [ ] Document crandb stuff in pkgsearch docs

- [ ] Take care of crandb rev dep (scripts using internal functions)

- [ ] Do something with crandb repo https://github.com/r-hub/crandb/issues/56

- [ ] Transfer crandb issues somewhere? E.g. where should API issues go?

**Comment by maelle** [comment]
I opened two PRs in other repos to make them use pkgsearch instead of crandb

* https://github.com/r-hub/cranatgh/pull/11

* https://github.com/metacran/cron/pull/9
