### ISSUE TITLE
Release pkgsearch 3.0.0

### ISSUE THREAD

**Issue by maelle** [r-hub/pkgsearch#22]
* [x] Change pkgdown mode cf https://pkgdown.r-lib.org/reference/build_site.html?q=mode#development-mode

* [x] https://github.com/r-hub/pkgsearch/pull/47

* [x] add-in cf #19 

* [x] advanced search cf #23

* [x] https://github.com/r-hub/pkgsearch/issues/41

Prepare for release: 
 
* [x] `devtools::check()` 
* [x] ~~`devtools::check_win_devel()`~~ _takes forever..._
* [x] `rhub::check_for_cran()` 
* [x] `revdepcheck::revdep_check(num_workers = 4)` 
* [x] [Polish NEWS](https://style.tidyverse.org/news.html#news-release) 
* [x] Polish pkgdown reference index 
* [x] Draft blog post 
 
Submit to CRAN: 
 
* [x] Bump version.
* [x] Submit to CRAN
* [x] Approve email 
 
Wait for CRAN... 
 
* [x] Accepted :tada: 
* [x] Add GitHub release
* [x] Bump to dev version.
* [ ] Finish blog post.
* [ ] Tweet 
* [x] ~~https://github.com/r-hub/crandb/pull/57~~

**Comment by gaborcsardi** [comment]
Do we want to discuss the crandb functions in the README a bit?

**Comment by maelle** [comment]
Yes, that's under "Update docs" :-D I opened this issue mostly to not forget to add an item about pkgdown mode :wink:

**Comment by gaborcsardi** [comment]
Will do the tweet and the blog post after 3.0.1, #81.
