### ISSUE TITLE
advanced search

### ISSUE THREAD

**Issue by gaborcsardi** [r-hub/pkgsearch#23]
e.g. restrict hits by field.

**Comment by maelle** [comment]
at the moment the possible fields are "Package^20", "Title^10", "Description^2", "Author^5", "Maintainer^6", "_all" <- what is "_all"?

**Comment by maelle** [comment]
the advanced search should allow to query anything on any of these fields, the API could handle that right? So the function arguments would be package_q, title_q, description_q, author_q, maintainer_q? (and maybe _all_q depending on what "_all" is :-) ).

Not sure however how to construct the query object, i.e. for each field what type(s)/boost(s) should be used.

**Comment by maelle** [comment]
Current query object construction, probably optimized somehow

```
  query_object <- list(
    query = list(
      function_score = list(
        functions = list(
          list(
            field_value_factor = list(
              field = "revdeps",
              modifier = "sqrt",
              factor = 1)
          )
        ),

        query = list(
          bool = list(
            ## This is simply word by work match, scores add up for fields
            must = list(
              list(multi_match = list(
                     query = query,
                     type = "most_fields"
                   ))
            ),
            should = list(
              ## This is matching the complete phrase, so it takes priority
              list(multi_match = list(
                     query = query,
                     fields = c("Title^10", "Description^2", "_all"),
                     type = "phrase",
                     analyzer = "english_and_synonyms",
                     boost = 10
                   )),
              ## This is if all words match (but not as a phrase)
              list(multi_match = list(
                     query = query,
                     fields = fields,
                     operator = "and",
                     analyzer = "english_and_synonyms",
                     boost = 5
                   ))
            )
          )
        )
      )
    )
  )

```

**Comment by maelle** [comment]
the addin #19 would support advanced search rather than simple search.

**Comment by gaborcsardi** [comment]
I think the addin should support both, defaulting to simple search.

Advanced search would simply let you filter to various fields, but otherwise use the same ranking.

**Comment by gaborcsardi** [comment]
I.e. similarly to https://github.com/search vs https://github.com/search/advanced

**Comment by maelle** [comment]
> Advanced search would simply let you filter to various fields, but otherwise use the same ranking.

I am not sure I understand what this means given the current search below

```
query_object <- list(
    query = list(
      function_score = list(
        functions = list(
          list(
            field_value_factor = list(
              field = "revdeps",
              modifier = "sqrt",
              factor = 1)
          )
        ),

        query = list(
          bool = list(
            ## This is simply word by work match, scores add up for fields
            must = list(
              list(multi_match = list(
                     query = query,
                     type = "most_fields"
                   ))
            ),
            should = list(
              ## This is matching the complete phrase, so it takes priority
              list(multi_match = list(
                     query = query,
                     fields = c("Title^10", "Description^2", "_all"),
                     type = "phrase",
                     analyzer = "english_and_synonyms",
                     boost = 10
                   )),
              ## This is if all words match (but not as a phrase)
              list(multi_match = list(
                     query = query,
                     fields = fields,
                     operator = "and",
                     analyzer = "english_and_synonyms",
                     boost = 5
                   ))
            )
          )
        )
      )
    )
  )
```

:thinking:

**Comment by maelle** [comment]
https://www.elastic.co/guide/en/elasticsearch/reference/current/getting-started-query-lang.html

**Comment by maelle** [comment]
Questions:
- How was the current query optimized?
- There is a huge number of possible fields, do we really want to make all of them available via the advanced search?
- If we only make some fields available via the advanced search, could we imagine a more low-level function where users provide their query JSON?
- I still don't understand "Advanced search would simply let you filter to various fields, but otherwise use the same ranking." . Especially if compared to GitHub search. I'd imagine the function lets the user chooses a filter value for fieldA, fieldB, etc. and the query is then

```r
query_object <- list(
    query = list(
        query = list(
          bool = list(
            ## This is simply word by work match, scores add up for fields
           
            must = list(
              ## This is matching the complete phrase, so it takes priority
              list(multi_match = list(
                     query = query,
                     fields = "fieldA",
                     type = "phrase",
                     analyzer = "english_and_synonyms",
                     boost = 10
                   )),
              ## This is if all words match (but not as a phrase)
              list(multi_match = list(
                     query = query,
                     fields = "fieldA",
                     operator = "and",
                     analyzer = "english_and_synonyms",
                     boost = 5
                   ))
            )
          )
        )
      )
    )
  )
```
plus something doing the same for the other fields (not sure how yet, I need to read more docs).
so not the same ranking?

**Comment by maelle** [comment]
I've started working on a draft PR to make things less theoretical.

In the add-in, ideally one would click on advanced and get all these boxes, and when clicking on search the top of the gadget would collapse otherwise one would not be able to see the results table in RStudio viewer.

**Comment by maelle** [comment]
I wouldn't add advanced search to the existing add-in PR btw (where IMO the focus is more on the add-in infrastructure and the look of the results). Once the add-in and the advanced search function exist, I'd make a new PR extending the add-in to accommodate advanced search. :-)

**Comment by gaborcsardi** [comment]
Done.
