### ISSUE TITLE
query() fails but service is running

### ISSUE THREAD

**Issue by restonslacker** [r-hub/pkgsearch#38]
I'm not sure if this issue is more appropriate here or in metacran/spareserver, but essentially what is happening is that ping test run by `robust_q` fails. I assume that this is because of my company's network configuration.  However, if I debug `ping_server` and manually set `server$state <- "on"` just before it returns, the query returns properly.  

It doesn't look like there's an easy way to add an option like "if this fails, try it anyway." The ping test seems to be about determining which server to use but if none pass the test, it doesn't seem like there is anything to lose by just trying one of them. Thoughts?

**Comment by gaborcsardi** [comment]
We are not using spareserver any more, so this should be gone.
