### ISSUE TITLE
Show results on the web

### ISSUE THREAD

**Issue by gaborcsardi** [r-hub/pkgsearch#4]
Probably just open a web page to http://cran.github.io.

**Comment by maelle** [comment]
still a project? [`packagefinder`](https://github.com/jsugarelli/packagefinder) has two options btw, console vs viewer.

**Comment by maelle** [comment]
What would need to be done?

**Comment by gaborcsardi** [comment]
IDK. Maybe redirect to `r-pkg.org`? But then the results might be different.... 

Alternatively, pretty-print the search hits into HTML and show them in the browser/viewer?

But I would not worry about this issue too much, basically wishlist.

**Comment by maelle** [comment]
With `formattable`, that packagefinder uses, you could have something simple like the code below (that formats URLs as html URLS to make them clickable)

```r
r_hub <- pkgsearch::ps("r-hub")

r_hub$url <- lapply(r_hub$url, strsplit, ",")

format_url <- function(url){
  paste0('<a href="', url, '">', url, '</a>')
}

format_urls <- function(urls){
  l <- unlist(lapply(urls, format_url))
  toString(l)
}

r_hub$url <- lapply(r_hub$url, format_urls)
r_hub$bugreports <- format_url(r_hub$bugreports)
r_hub$package <- format_url(paste0("https://r-pkg.org/pkg/", r_hub$package))
formattable::formattable(r_hub)
```

And the last line opens a table in RStudio Viewer, that you can open in a web browser. In a R session without RStudio, it's directly opened in a web browser.

**Comment by gaborcsardi** [comment]
formattable seems heavy and unmaintained. I think we can just ignore this issue now.

**Comment by maelle** [comment]
My work in #51 is related to this issue because the addin creates a datatable that can be viewed in the RStudio viewer or in the web browser, with clickable links (package name, URL, BugReport). The package name links to the r-pkg.org page of the package.

**Comment by gaborcsardi** [comment]
I am closing this in favor of the addin.
