### ISSUE TITLE
Add API to list orphaned packages

### ISSUE THREAD

**Issue by gaborcsardi** [r-hub/pkgsearch#40]

**Comment by maelle** [comment]
Would adding the view + writing contributing guidelines and a blog post be useful? To recruit contributors for other crandb issues?

**Comment by gaborcsardi** [comment]
This is now simple: 

```
advanced_search(Maintainer = "ORPHANED")
```

**Comment by maelle** [comment]
Very cool! Should we add this as an example to the function before closing the issue?

**Comment by gaborcsardi** [comment]
I did already.
