### ISSUE TITLE
what URL to use to refer to crandb webservice?

### ISSUE THREAD

**Issue by maelle** [r-hub/pkgsearch#44]
For search I use https://github.com/metacran/search

**Comment by gaborcsardi** [comment]
to the docs?

**Comment by maelle** [comment]
which docs?

**Comment by gaborcsardi** [comment]
Maybe I don't understand then. Where do we need to put this link?

**Comment by maelle** [comment]
In https://r-hub.github.io/pkgsearch/#search-cran-packages-with-pkgsearch there's a link to the web service corresponding to search, and I'd like to add such a link for the former crandb functions.

**Comment by gaborcsardi** [comment]
Well, technically, the search service is at http://search.r-pkg.org/ and CRANDB is at crandb.r-pkg.org, right now.

**Comment by maelle** [comment]
Should I link to crandb.r-pkg.org? Or the source of that (which I'm not sure I know)?

**Comment by gaborcsardi** [comment]
Yeah, I think we can just link there. The source is here: https://github.com/r-hub/crandb/blob/master/inst/app.js but that might change.

**Comment by maelle** [comment]
Oh right, if we archive that repo, this will need to move? Or the repo could contain just that and no package stuff?

**Comment by gaborcsardi** [comment]
IDK, we'll see.
