### ISSUE TITLE
Use of keywords in DESCRIPTION and in search

### ISSUE THREAD

**Issue by maelle** [r-hub/pkgsearch#48]
I've tried finding https://cran.r-project.org/web/packages/paws/index.html via `pkgsearch::ps("aws", size = 100)`. It didn't appear. I assume it's because the aws abbreviation is only present in an URL? Is this an example of why authors should think about keywords folks might use to find their package? E.g. in this case would it be sufficient to replace "Interface to Amazon Web Services" with "Interface to Amazon Web Services ('AWS')" in the package Description?

**Comment by gaborcsardi** [comment]
Yeah, keywords would be great.

**Comment by maelle** [comment]
So it's something the authors should pay attention to, right? It's something I'll mention in the blog post but I wonder whether it could/should be part of the package docs too. :thinking:

**Comment by gaborcsardi** [comment]
IDK, what is the best way to put keyworks into `DESCRIPTION`?

**Comment by maelle** [comment]
You can use `X.schema.org` stuff cf e.g. https://github.com/ropensci/codemetar/blob/0630dc38c48f594b48ad708707248a37d129dba6/DESCRIPTION#L100 and CRAN won't complain (thanks to @cboettig). Such info doesn't appear on the CRAN page, but could the search API use it?

**Comment by gaborcsardi** [comment]
The search server indexes all fields, so yeah they will be found. But should we advertise this as the correct way to add keywords? If this is the standard way, then we should up-weight the search hits for this field.

**Comment by maelle** [comment]
there's no standard way AFAIK. Maybe we should rather recommend to pack as many keywords as possible in Description.

**Comment by gaborcsardi** [comment]
I think having an explicit keyword field would be nice.

**Comment by gaborcsardi** [comment]
But until then we can also use the `X.schema.org` stuff....

**Comment by maelle** [comment]
especially as it was already CRAN-approved. In `codemetar` we even discussed a possible helper function that'd take GitHub topics of a repo and write them as `X.schema.org` keywords in DESCRIPTION cf https://github.com/ropensci/codemetar/pull/152 but I'm not sure where such a function should live, probably not pkgsearch.

**Comment by maelle** [comment]
Interestingly at the time of that convo in `codemetar` I noted that having (schema.org) keywords in DESCRIPTION was useless if not for inclusion in the codemeta.json (whereas GitHub topics are useful or at least can be, for folks who browse topics), but if the search API used those, then keywords in DESCRIPTION would be useful for sure!

**Comment by maelle** [comment]
at the moment not that many results for https://github.com/search?p=1&q=X-schema.org-keywords+user%3Acran&type=Code, and most of them seem to be rOpenSci packages. 

I'm not sure we can revolutionize CRAN before the next pkgsearch release but in the release blog post I could show the use of advanced search on that field and mention package developers could use this field for keywords. :thinking:

**Comment by gaborcsardi** [comment]
Closing, as it does not seem to be actionable.
