### ISSUE TITLE
cran_package_list()/cran_active_packages() vs tools::CRAN_package_db()

### ISSUE THREAD

**Issue by maelle** [r-hub/pkgsearch#49]
This question concerns the function in progress in #47 

Why recommend the two first functions other the latter one?

I've thought of

* speed

* output format (better for the pkgsearch in progress functions)

Related question, is it ok to set whatever `limit` in the crandb functions i.e. fine to query all CRAN packages at once?

**Comment by maelle** [comment]
@gaborcsardi any insight?

**Comment by gaborcsardi** [comment]
We don't need to recommend them.

Yes, whatever limit is OK, for now.

**Comment by maelle** [comment]
I was thinking the crandb database also holds _more_ data than what R's built-in function returns.
