### ISSUE TITLE
another thing that depends on crandb

### ISSUE THREAD

**Issue by maelle** [r-hub/pkgsearch#50]
https://github.com/r-lib/pkgdown/blob/a2e7b262c6db857014a24cbaf1c8ec2921e59f2c/R/build-news.R#L216

**Comment by gaborcsardi** [comment]
Good digging. This uses the HTTP API, so we don't need to do anything I believe.

**Comment by maelle** [comment]
well unless the URL changes?

I'll mention that in the blog post, it's a cool use case of the data. I found it randomly when trying to see whether pkgdown uses GitHub API at all (doesn't seem so).

**Comment by gaborcsardi** [comment]
Closing this, you already aa reference from the blog post issue, to remind you.
