### ISSUE TITLE
Trending packages?

### ISSUE THREAD

**Issue by gaborcsardi** [r-hub/pkgsearch#54]
Maybe also "package of the day"?

**Comment by maelle** [comment]
Related work https://github.com/vitalets/github-trending-repos/issues/39

**Comment by maelle** [comment]
`cran_trending()` will always return **100** packages, correct? I can add that to the docs.

What would be a package of the day, one line from `cran_trending()`?

**Comment by maelle** [comment]
Could `cran_trending()` and `cran_top_downloaded()` return the same metadata as `ps()`? To better help discover packages.

Besides, could the doc of the trending function have a link to the code sorting packages?

**Comment by gaborcsardi** [comment]
They should, ideally, but that's not in the crandb api currently. We can do that later.

**Comment by gaborcsardi** [comment]
We have trending packages now. It is very basic, but will do for this release.
