### ISSUE TITLE
Failure on CI

### ISSUE THREAD

**Issue by maelle** [r-hub/pkgsearch#55]
Both Travis and Appveyor

```r
> test_check("pkgsearch")
  Error in pkgdata$config[[key]] <<- value : 
    cannot change value of locked binding for 'pkgdata'
  Calls: test_check ... eval -> eval -> cran_mirror -> getset_config -> set_config
  Execution halted
```

**Comment by gaborcsardi** [comment]
Yeah, I'll get rid of all that stuff, it is seriously messed up. I don't know what I was doing there....

**Comment by maelle** [comment]
Once it is solved the pkgdown website will be updated :-)

**Comment by maelle** [comment]
Yay 👏 @gaborcsardi!

Could you review #59 to update the docs website? 🙂
