### ISSUE TITLE
update README

### ISSUE THREAD

**Issue by maelle** [r-hub/pkgsearch#58]
and add vignette(s)

**Comment by maelle** [comment]
Right now I'm thinking of moving the details of search to a specific search vignette. 

The pkgsearch.Rmd ("get started") would have approximately the same content as the README minus installation instructions.

**Comment by gaborcsardi** [comment]
Honestly, I am not sure if it is worth adding a vignette. Maybe this
package is small enough to put everything in the README? In any case,
the bulk of the work is writing the text, and then we can decide where
to put it. :)

**Comment by gaborcsardi** [comment]
Fixed by #59.
