### ISSUE TITLE
Should the examples be in \dontrun?

### ISSUE THREAD

**Issue by maelle** [r-hub/pkgsearch#60]

**Comment by gaborcsardi** [comment]
Working on this.

**Comment by maelle** [comment]
it seems done?

**Comment by gaborcsardi** [comment]
not really.

**Comment by maelle** [comment]
btw is there an automatic way to assess how many examples are in dontrun?

**Comment by gaborcsardi** [comment]
IDK, you can parse them and count the lines, but IDK if it's worth it....
code coverage by examples  is a measure I guess

**Comment by maelle** [comment]
"code coverage by examples  is a measure I guess" do you mean it's provided by something?

**Comment by gaborcsardi** [comment]
> "code coverage by examples is a measure I guess" do you mean it's provided by something?

```r
covr::package_coverage(type = "examples")
```

**Comment by gaborcsardi** [comment]
We'll rather do
```r
#' \dontshow{ if (pingr::is_online()) withAutoprint(\{ }
#' ...
#' \dontshow{ \}) }
```
