### ISSUE TITLE
Can one write anything in advanced search

### ISSUE THREAD

**Issue by maelle** [r-hub/pkgsearch#62]
E.g. could one use 

```
{
    "query": {
        "bool": {
            "must_not": {
                "exists": {
                    "field": "URL"
                }
            }
        }
    }
}
```

**Comment by maelle** [comment]
I wonder about that because seeing the example for packages that have the URL field makes me want to find the ones that don't. :grin:

**Comment by maelle** [comment]
Ok, I'll add the example to docs.

Regarding arbitrary JSON does it already work or should it be an enhancement?

**Comment by gaborcsardi** [comment]
No, it does not work, it could probably work through an extra argument to `advanced_search()`. We could call it `json`, maybe.

**Comment by maelle** [comment]
Ok, I'll make a PR.

**Comment by maelle** [comment]
oh you added it :joy:
