### ISSUE TITLE
Document overlap with cranlogs?

### ISSUE THREAD

**Issue by maelle** [r-hub/pkgsearch#66]
E.g. `cranlogs::cran_top_downloads(when = "last-week", count = 100)` = `pkgsearch::cran_top_downloaded()`

**Comment by maelle** [comment]
And actually why don't the functions using cranlogs live in cranlogs? :thinking:

**Comment by gaborcsardi** [comment]
I think a bit of duplication is fine.

**Comment by gaborcsardi** [comment]
We could, sure, the latter is not really urgent, though.

**Comment by maelle** [comment]
https://github.com/r-hub/cranlogs/issues/47

**Comment by maelle** [comment]
Fixed in #68
