### ISSUE TITLE
Addin page title in the browser is `<div> <div>...`

### ISSUE THREAD

**Issue by gaborcsardi** [r-hub/pkgsearch#75]

**Comment by maelle** [comment]
I can't open the addin in the browser, how do you do that?

**Comment by maelle** [comment]
Ah I see.

**Comment by maelle** [comment]
https://stackoverflow.com/questions/51688463/shiny-page-title-and-image

**Comment by maelle** [comment]
Ah now that's easy actually https://shiny.rstudio.com/reference/shiny/0.11/headerPanel.html will make a PR in a sec

**Comment by gaborcsardi** [comment]
Fixed by #79.
