### ISSUE TITLE
My packages is broken in the addin.

### ISSUE THREAD

**Issue by gaborcsardi** [r-hub/pkgsearch#76]

**Comment by maelle** [comment]
top packages (most depended upon) too (same error). am on it.

**Comment by maelle** [comment]
TIL "git log -S" :smile_cat: 

https://github.com/r-hub/pkgsearch/commit/2d9453dbce330a63c57c923948cb598996447cce

**Comment by gaborcsardi** [comment]
Fixed by #77.
