### ISSUE TITLE
Weird addin bug

### ISSUE THREAD

**Issue by maelle** [r-hub/pkgsearch#78]
If I use the addin from RStudio, after that I can't close RStudio. It says "Quitting R session" forever. I can close the addin though, just not RStudio after that.

Not sure where the bug comes from. I'm using it on Ubuntu.

**Comment by maelle** [comment]
Actually when I close the addin, my R session is no longer responsive.

**Comment by gaborcsardi** [comment]
I don't really see how that could be the addin's fault, seems like a Shiny or RStudio bug to me.

**Comment by gaborcsardi** [comment]
https://github.com/rstudio/shiny/issues maybe?

**Comment by maelle** [comment]
I'll start with community.rstudio.com.

**Comment by maelle** [comment]
https://community.rstudio.com/t/rstudio-r-session-hanging-after-running-an-addin/45088

**Comment by gaborcsardi** [comment]
Also, try updating the related packages if you can: shiny, httpuv, later, promises.

**Comment by maelle** [comment]
I've updated all dependencies, and the bug only happens after running code in the addin. Opening and closing it doesn't ruin the R session.

**Comment by gaborcsardi** [comment]
This might be related, I get this on macOS:
```
 Error in execCallbacks(timeoutSecs, all, loop$id) : 
  invoke_wrapped: throwing std::runtime_error 

18. stop(e) 
17. (function (e) 
{
    if (is.null(attr(e, "stack.trace", exact = TRUE))) {
        calls <- sys.calls() ... 
16. stop(structure(list(message = "invoke_wrapped: throwing std::runtime_error", 
    call = execCallbacks(timeoutSecs, all, loop$id), cppstack = NULL), class = c("std::runtime_error", 
"C++Error", "error", "condition"))) 
15. execCallbacks(timeoutSecs, all, loop$id) 
14. force(expr) 
13. with_loop(loop, invisible(execCallbacks(timeoutSecs, all, loop$id))) 
12. run_now(timeoutMs/1000, all = FALSE) 
11. service(timeout) 
10. serviceApp() 
9. ..stacktracefloor..(serviceApp()) 
8. withCallingHandlers(expr, error = doCaptureStack) 
7. domain$wrapSync(expr) 
6. promises::with_promise_domain(createStackTracePromiseDomain(), 
    expr) 
5. captureStackTraces({
    while (!.globals$stopped) {
        ..stacktracefloor..(serviceApp())
    } ... 
4. ..stacktraceoff..(captureStackTraces({
    while (!.globals$stopped) {
        ..stacktracefloor..(serviceApp())
    } ... 
3. shiny::runApp(app, port = port, launch.browser = viewer) 
2. shiny::runGadget(ui, server, viewer = viewer) at addin.R#484
1. pkg_search_addin() 
```

**Comment by gaborcsardi** [comment]
My brave and very uneducated guess is that we might fix this by adding an "Done" button. But how can we do that?

**Comment by maelle** [comment]
Let me have a look!

**Comment by gaborcsardi** [comment]
Ideally it would in the top right of the navbar, but that looks hard to do.... unless I am missing something.

**Comment by maelle** [comment]
I'm wondering what other addin is doing something similar. addinlist itself doesn't really run R code (but depends on shinyjs).

**Comment by gaborcsardi** [comment]
I guess most addins use miniUI.
