### ISSUE TITLE
Add a go button to the "My packages" addin tab

### ISSUE THREAD

**Issue by maelle** [r-hub/pkgsearch#82]
I've just noticed this when recording my 1,000th screencast :wink:

If you delete the email address and start typing one, you get errors until the email address is typed. It'd be good to be able to click on "go" to prevent the addin from performing the search on an incomplete email address.

**Comment by gaborcsardi** [comment]
We could also just not search until we have an email address, i.e. sth with a `@`. This will still do incomplete searches, but then we can just output "No packages found" or something like that.

But the Go button is not bad, either.
