### ISSUE TITLE
Include file size(s) in cran_package_history()

### ISSUE THREAD

**Issue by lindbrook** [r-hub/pkgsearch#95]
Would it be possible to include file sizes in cran_package_history()? For an example see: [A3](https://cran.r-project.org/src/contrib/Archive/A3/).

**Comment by gaborcsardi** [comment]
That is currently not in the database. Why is it useful?

**Comment by lindbrook** [comment]
So I can filter out other "small" downloads besides the ~500 B entries.

**Comment by lindbrook** [comment]
This may not be as useful as I thought. The logs record downloads of both source and binary files but CRAN only keeps the source files of prior versions. So it seems I can only get the size of source files not binaries. This is problematic for my purposes because binaries aren't strictly larger than source files.
